version: '3.7'

services:

  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=terraform
      - POSTGRES_DB=terraform
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  vault:
    container_name: vault
    image: vault
    hostname: vault
    environment:
      - -dev
      - VAULT_DEV_ROOT_TOKEN_ID=root
    ports:
      - 8200:8200

volumes:
  postgres:
