name: terraform

on:
  push:

jobs:

  terraform:
    runs-on: ubuntu-latest
    steps:

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: terraform run
        run: |
          for i in $(find providers/ | grep backend.tf | grep aws | grep network | sed 's/\/backend.tf//g') ; do
            cd $i
            terraform init
            terraform validate
            terraform plan
          done
