name: terraform

on:
  push:

jobs:

  terraform:
    runs-on: ubuntu-latest
    steps:

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: terraform init
        id: init
        working-directory: providers/aws/environments/dev/global/network
        run: terraform init
        continue-on-error: false

      - name: terraform validate
        id: validate
        working-directory: providers/aws/environments/dev/global/network
        run: terraform validate
        continue-on-error: false

      - name: terraform plan
        id: plan
        working-directory: providers/aws/environments/dev/global/network
        run: terraform plan
        continue-on-error: false

        #- name: terraform apply
        #  id: apply
        #  working-directory: ./aws/environments/dev/global/network
        #  run: terraform apply -auto-approve
        #  continue-on-error: false
